### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by mobiuscoffee** [zeekay/soundcloud-cli#3]
I tried to use `$ sc auth` on an account that used unicode in its name and it connected, but gave an error.

```
Traceback (most recent call last):
  File "/usr/local/bin/sc", line 3, in <module>
    cli.main()
  File "/home/john/.local/lib/python2.7/site-packages/soundcloud_cli/cli.py", line 216, in main
    args.command(args)
  File "/home/john/.local/lib/python2.7/site-packages/soundcloud_cli/cli.py", line 23, in command_auth
    user_input = raw_input('enter username ({0}): '.format(username))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-10: ordinal not in range(128)
```
Also, if I tried to use `sc auth` again it just gave the same error and would not let me change accounts.

Deleting `~/.sc` stopped the error and allowed me to authenticate another account, as long as it didn't have unicode in it.

**Comment by zeekay** [comment]
Should be fixed in 0.2.7. Let me know if you have any other issues!

**Comment by mobiuscoffee** [comment]
> Should be fixed in 0.2.7. Let me know if you have any other issues!

A reinstall with pip should fix everything then?

**Comment by zeekay** [comment]
Well, that error at least :)

**Comment by mobiuscoffee** [comment]
I get the same error if i use `sc list` and the user has tracks in unicode.

**Comment by mobiuscoffee** [comment]
would this fix work for the `sc list` problem as well? If so, I'll try it out when I have the time!

**Comment by zeekay** [comment]
I need to update soundcloud-cli to use unicode internally. I'll take a look at that later this evening!
