### ISSUE TITLE
Cannot use sc anymore "ImportError"

### ISSUE THREAD

**Issue by mobiuscoffee** [zeekay/soundcloud-cli#7]
I recently went through reinstalling everything on a new computer, but I'm having some trouble getting soundcloud-cli to work.

Every time I use `sc` I get this error:
```
~$ sc
Traceback (most recent call last):
  File "/usr/local/bin/sc", line 2, in <module>
    from soundcloud_cli import cli
  File "/usr/local/lib/python3.4/dist-packages/soundcloud_cli/__init__.py", line 3, in <module>
    import api
```

I think it has something to do with python versions, but I have no idea what to do.

**Comment by zeekay** [comment]
I would rm /usr/local/bin/sc and pip install soundcloud-cli again.

**Comment by zeekay** [comment]
It's also not particularly Python 3 ready.

**Comment by mobiuscoffee** [comment]
using `rm /usr/local/bin/sc` and reinstalling worked perfectly.

A small detail though. My system has defaulted to pip3 for some reason, so I had to use `pip2` to install correctly. In any case `pip2 install soundcloud-cli` worked perfectly.
